# Generated by Django 4.0.3 on 2022-07-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_create_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='starts',
            field=models.DateField(),
        ),
    ]
