# Generated by Django 4.0.3 on 2022-07-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_conference_ends_alter_conference_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ends',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='starts',
            field=models.DateTimeField(),
        ),
    ]
