# Generated by Django 4.0.3 on 2022-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_conference_ends_alter_conference_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ends',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='starts',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
