# Generated by Django 4.0.3 on 2022-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_conference_ends_alter_conference_starts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='ends',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='starts',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
